version: 0.2
phases:
  install:
    commands:
      - cd pageripper && GOOS=linux GOARCH=amd64 go build
      - cd ..
      - aws cloudformation package --template-file template.yaml --s3-bucket pageripper-serverless --output-template-file packaged.yaml
artifacts:
  files:
    - packaged.yaml
