version: 0.1
phases:
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - cd ui && npm install
  build:
    commands:
      - echo Build started on `date`
      - cd ui && npm run build
artifacts:
  files:
    - '**/*'
  base-directory: ./ui/build
