version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      # change directory to where the UI source files live - note that in buildspec v0.2 we only have to run cd once at the beginning
      - cd ui
      # Install react dependencies
      - echo Installing NPM dependencies...
      - npm install
  build:
    commands:
      # Build react frontend app
      - npm run build
artifacts:
  files:
    - '**/*'
cache: 
  paths: 
    - './node_modules/**/*'
