version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "pageripper-sam"
s3_bucket = "pageripper-serverless"
s3_prefix = "pageripper-sam"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
