AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Serverless Pageripper app leveraging AWS Serverless Application Model

Globals:
  Function:
    Timeout: 6

  Api:
    Cors:
      AllowMethods: "'GET,POST,OPTIONS'"
      AllowHeaders: "'*'"
      AllowOrigin: "'*'"

Resources:
  # The Lambda Golang function
  PageRipperFunction:
    Type: AWS::Serverless::Function
    Properties:
      # All the source code is defined in the ./pageripper/ directory
      CodeUri: pageripper/
      Handler: pageripper
      # Our runtime is Go
      Runtime: go1.x
      # We want Xray enabled
      Tracing: Active
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: "/{proxy+}"
            Method: ANY
      Policies:
        # This is a convenience policy allowing our Lambda template to perform CRUD operations on the Lambda table
        - DynamoDBCrudPolicy:
            TableName: !Ref DynamoDBTable

  # Create the DynamoDB table that the pageripper app stores counts in
  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: pageripper
      AttributeDefinitions:
        - AttributeName: url
          AttributeType: S
        - AttributeName: c
          AttributeType: N
      KeySchema:
        - AttributeName: url
          KeyType: HASH
        - AttributeName: c
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  PageripperAPI:
    Description: "API Gateway endpoint URL for Prod environment for Pageripper Function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/rip/"
    Export:
      Name: !Sub "${AWS::StackName}-URL-API"
  PageRipperFunction:
    Description: "Pageripper Function ARN"
    Value: !GetAtt PageRipperFunction.Arn
  PageRipperFunctionIamRole:
    Description: "Implicit IAM Role created for Pageripper function"
    Value: !GetAtt PageRipperFunctionRole.Arn
